# Generated by Django 3.2.5 on 2021-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='text_blob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
