# Generated by Django 3.2.5 on 2021-07-29 10:17

from django.db import migrations
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('render_doc', '0002_block_text_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='yaml_data',
            field=yamlfield.fields.YAMLField(blank=True, null=True),
        ),
    ]
