# Generated by Django 3.2.5 on 2021-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_doc', '0004_remove_block_yaml_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='text_blob',
            field=models.CharField(blank=True, max_length=1048576, null=True),
        ),
    ]
