# Generated by Django 3.2.5 on 2021-07-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_doc', '0005_alter_block_text_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='text_yaml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
